In [2]:
import numpy as np

In [27]:
#array operation
a= np.array([[[1,1],[2,2],[3,3]],[[4,4],[5,5],[6,6]]])
print(a)
print(np.shape(a))
b=a.T
print(b)
print(np.shape(b))
c=a*a
print(c)
a=np.array([[1,2,3],[4,5,6]])
b=a.T                   #'.T'为取倒置
d=np.dot(a,b**2)        #dot为点乘
print(d)

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]
(2, 3, 2)
[[[1 4]
  [2 5]
  [3 6]]

 [[1 4]
  [2 5]
  [3 6]]]
(2, 3, 2)
[[[ 1  1]
  [ 4  4]
  [ 9  9]]

 [[16 16]
  [25 25]
  [36 36]]]
[[ 36 174]
 [ 78 405]]


In [28]:
#tuple
a=(23,[34,1,7],'ee')
print(type(a))

<class 'tuple'>


In [31]:
#dictionary
d={'one':1,'two':2,'three':3}
print(d)
print(d['two'])
d['four']=4
d['three']=33
print(d)

{'one': 1, 'two': 2, 'three': 3}
2
{'one': 1, 'two': 2, 'three': 33, 'four': 4}


How to write a loop in python

In [34]:
#for loop
for i in range (10):
    print(i)
print(' ')
for i in range(0,10,3):
    print(i)

0
1
2
3
4
5
6
7
8
9
 
0
3
6
9


In [48]:
#if else
for i in range(10):
    if np.mod(i,2)==0:     #mod为取余数
        print(i,i/2)
    elif np.mod(i,3)==0:
        print(i,i/3)
    elif np.mod(i,5)==0:
        print(i,i/5)
    else:
        print(i)

0 0.0
1
2 1.0
3 1.0
4 2.0
5 1.0
6 3.0
7
8 4.0
9 3.0


In [138]:
#%matplotlib inline
%pylab

import matplotlib.pyplot as plt
import matplotlib
matplotlib.rc('xtick',labelsize=12)   #X轴刻度字体大小
matplotlib.rc('ytick',labelsize=12)

x=np.random.rand(10)    #X轴随机取10个点,默认范围0-1
x=np.sort(x)
y=np.arctan(x)     #函数关系

fig=plt.figure()   #调用画板，大小默认
ax=fig.add_subplot(111)   #分割画板，(纵向，横向，位置)
ax.plot(x,y,'k+',markersize=12)   #取的点的形状('+')及大小
ax.plot(x,y,'r--')               #曲线为虚线
ax.set_xlabel('X',fontsize=12)   #X轴的标注，及字体大小
ax.set_ylabel(r'$\arctan{\theta}$',fontsize=12)   #Y轴标注及字体大小
fig.show()

Using matplotlib backend: TkAgg
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [18]:
x=np.random.normal(0,10,size=10000)   #随机正态散点图，x的大小为10000,即随机取了10000个点，0为质心，10为弥散程度
#类似于在10000s内，每秒打一个点，即时变曲线。

xgrid=np.arange(-100,105,5)   #统计曲线图，(-100,105)为X轴范围，5为间隔大小
xcenter=(xgrid[1:]+xgrid[:-1])/2   #曲线横轴，每个间隔的中间点相连。如间隔[15,20),就取17.5。
hx,xedge=np.histogram(x,bins=xgrid)   #直方图

fig=plt.figure(figsize=[10,4])   #调用画板，设置画板大小，14为画板横向宽，6为画板纵向宽
ax=fig.add_subplot(121)   #分割画板，(纵向，横向，位置)，横向分割成两份，放在第一份。
ax.plot(x,'k.')   #取的点的形状为'.'，大小默认。

ax=fig.add_subplot(122)
ax.step(xedge[1:],hx,'k-')   #左闭右开区间，点的形状为‘-’。
ax.plot(xcenter,hx,'r-')   #曲线为实线
ax.set_xlabel(r'$y$',fontsize=12)   #x轴标注及字体大小
fig.show()

In [4]:
#%matplotlib inline
%pylab

import matplotlib.pyplot as plt
import matplotlib
#matplotlib.rc('xtick',labelsize=12)   #X轴刻度字体大小
#matplotlib.rc('ytick',labelsize=12)

import numpy as np

import scipy.stats as stats
import time

start=time.time()
mu=np.array([1,1])
s1=1
s2=0.2
rho=0.8   #s1,s2和rho的相对大小为图像的倾角，实际大小为图像的放大程度
sig=np.array([[s1,rho*np.sqrt(s1*s2)],[rho*np.sqrt(s1*s2),s2]])
#generate random numbers from 2D normal distribution
xx=np.random.multivariate_normal(mu,sig,100000)   #产生随机多元(xx表示二元)正态分布数据，mu为质心，sig为弥散程度
xgrid=np.arange(-2,4,0.2)   #x轴区间[-2,4]，间隔大小0.2
ygrid=np.arange(-2,4,0.2)   #y轴区间[-2,4]，间隔大小0.2
xcenter=(xgrid[0:-1]+xgrid[1:])/2   #曲线横轴取点
ycenter=(ygrid[0:-1]+ygrid[1:])/2   #曲线纵轴取点
#make 2d histogram
hxx,xedge,yedge=np.histogram2d(xx[:,0],xx[:,1],bins=[xgrid,ygrid])   #画二维直方图

fig=plt.figure(figsize=[14,6])   #调用画布，画布大小
plt.set_cmap('jet')
ax=fig.add_subplot(121)   #分割画布
ax.contour(xcenter,ycenter,hxx.T)   #设置轮廓
ax.set_xlabel(r'$x_1$',fontsize=20)   #横轴标注及大小
ax.set_ylabel(r'$x_2$',fontsize=20)   #纵轴标注及大小

ax=fig.add_subplot(122)   #分割画布
e=ax.imshow(hxx.T,extent=[xcenter[0],xcenter[-1],ycenter[-1],ycenter[0]])   #图在框框的分布(压缩？)
plt.colorbar(e)               #添加颜色对照条
ax.set_ylim([ycenter[0],ycenter[-1]])   #在框框中纵向移动图
ax.set_xlabel(r'$x_1$',fontsize=20)   #横轴标注及大小
ax.set_ylabel(r'$x_2$',fontsize=20)   #纵轴标注及大小

fig.show()
print('escape %(s).3f sec' % {'s':time.time()-start})

Using matplotlib backend: TkAgg
%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


/home/xsh/.local/lib/python3.9/site-packages/IPython/core/magics/pylab.py:162: UserWarning: pylab import has clobbered these variables: ['f']
`%matplotlib` prevents importing * from pylab and numpy
  warn("pylab import has clobbered these variables: %s"  % clobbered +


escape 0.147 sec


In [22]:
#read files

f=open('/home/xsh/下载/Riess1998_Tab5.txt')
#line=f.readline()
#print(line)
for line in f:
    cols=line.split()
    print(cols)
f.close()

['1996E', '0.43', '22.81(0.21)', '22.72(0.23)', '-0.08(0.19)', '0.31', '41.74(0.28)']
['1996H', '0.62', '23.23(0.19)', '23.56(0.18)', '-0.42(0.16)', '0.00', '42.98(0.17)']
['1996I', '0.57', '23.35(0.28)', '23.59(0.26)', '-0.06(0.26)', '0.00', '42.76(0.19)']
['1996J', '0.30', '22.23(0.12)', '22.21(0.11)', '-0.22(0.10)', '0.24', '41.38(0.24)']
['1996K', '0.38', '22.64(0.12)', '22.84(0.14)', '0.29(0.06)', '0.00', '41.63(0.20)']
['1996U', '0.43', '22.78(0.22)', '22.98(0.30)', '-0.52(0.29)', '0.00', '42.55(0.25)']
['1997ce', '0.44', '22.85(0.09)', '22.95(0.09)', '0.07(0.08)', '0.00', '41.95(0.17)']
['1997cj', '0.50', '23.19(0.11)', '23.29(0.12)', '-0.04(0.11)', '0.00', '42.40(0.17)']
['1997ck', '0.97', '24.78(0.25)', '\\ldots', '-0.19(0.23)', '\\ldots', '44.39(0.30)']
['1995K', '0.48', '22.91(0.13)', '23.08(0.20)', '-0.33(0.26)', '0.00', '42.45(0.17)']


In [23]:
#read ASCII file in a more comfortable way

from astropy.table import Table

data=Table.read('/home/xsh/下载/Riess1998_Tab5.txt',format="ascii.no_header")
print(data)

 col1  col2     col3        col4        col5     col6      col7   
------ ---- ----------- ----------- ----------- ------ -----------
 1996E 0.43 22.81(0.21) 22.72(0.23) -0.08(0.19)   0.31 41.74(0.28)
 1996H 0.62 23.23(0.19) 23.56(0.18) -0.42(0.16)   0.00 42.98(0.17)
 1996I 0.57 23.35(0.28) 23.59(0.26) -0.06(0.26)   0.00 42.76(0.19)
 1996J  0.3 22.23(0.12) 22.21(0.11) -0.22(0.10)   0.24 41.38(0.24)
 1996K 0.38 22.64(0.12) 22.84(0.14)  0.29(0.06)   0.00 41.63(0.20)
 1996U 0.43 22.78(0.22) 22.98(0.30) -0.52(0.29)   0.00 42.55(0.25)
1997ce 0.44 22.85(0.09) 22.95(0.09)  0.07(0.08)   0.00 41.95(0.17)
1997cj  0.5 23.19(0.11) 23.29(0.12) -0.04(0.11)   0.00 42.40(0.17)
1997ck 0.97 24.78(0.25)      \ldots -0.19(0.23) \ldots 44.39(0.30)
 1995K 0.48 22.91(0.13) 23.08(0.20) -0.33(0.26)   0.00 42.45(0.17)


In [2]:
#write ASCII file

import csv

rows=[[32,33,34],['a','b','c']]

with open("/home/xsh/test.csv","wt") as f:
    c_w=csv.writer(f,quoting=csv.QUOTE_NONE)
    c_w.writerows(rows)

In [32]:
#read a fits image file

import astropy.io.fits as fits

def readImage(filename):
    hdulist=fits.open(filename)
    im=hdulist[0].data.copy()
    hdulist.close()
    return im

im=readImage('/home/xsh/下载/image.fits')
fig=plt.figure()
plt.set_cmap('gray')
ax=fig.add_subplot(111)
e=ax.imshow(np.log(im))
plt.colorbar(e)
#ax.set_ylim()
fig.show()

/tmp/ipykernel_3593/1303598421.py:15: RuntimeWarning: invalid value encountered in log
  e=ax.imshow(np.log(im))


In [ ]:
#write an image from a fits file

import numpy
from astropy.io import fits as pyfits

fitsfile = pyfits.open('/home/xsh/下载/image.fits',mode='update')
image=fitsfile[0].data
header=fitsfile[0].header

#write image to a fits file

pyfits.writeto('/home/xsh/image_2.fits',image,header)

In [34]:
#Read table date from a fit file

def loadData(filename):
    #read fits data
    tchfits=fits.open(filename)
    tabl=tchfits[1].data.copy()
    return tabl

filename='/home/xsh/下载/ComaCluster.fits'
coma=loadData(filename)
cz=coma.czA[(coma.czA<20000)&(coma.czA>0)]
sig_cz=np.var(cz)
print(np.sqrt(sig_cz))
zgrid=np.arange(2000,12000,750)
h,xedge=np.histogram(cz,bins=zgrid)
fig=plt.figure(figsize=[6,4])
ax=fig.add_subplot(111)
ax.plot(zgrid[0:-1]+250,h,'k*-')
ax.set_xlabel('redshift(km/s)')
fig.show()

1316.8409611736695


In [23]:
from astropy.table import Table
filename='/home/xsh/下载/ComaCluster.fits'
coma=Table.read(filename)
print(coma)
cz=coma['czA'][(coma['czA']<20000)&(coma['czA']>0)]
sig_cz=np.var(cz)
print(np.sqrt(sig_cz))
zgrid=np.arange(2000,12000,750)
h,xedge=np.histogram(cz,bins=zgrid)
fig=plt.figure(figsize=[6,4])
ax=fig.add_subplot(111)
ax.plot(zgrid[0:-1]+250,h,'k*-')
ax.set_xlabel('redshift(km/s)')
fig.show()

 _RAJ2000 _DEJ2000  S    ID   f_ID  PT ...  czA   e_czA  S/N  MType A06 Simbad
   deg      deg                        ... km / s km / s                      
--------- -------- --- ------ ---- --- ... ------ ------ ---- ----- --- ------
 194.8585 28.01778  Mm 132151        4 ...   5486    130  6.3   ImV   1 Simbad
194.87846 28.04187  Mm 133494        2 ...   6549     77 44.6   E     0 Simbad
194.88221 27.96338  Mm 190797        3 ...   8860     74  5.0   dE    1 Simbad
194.89312 27.99539  Mm 191169        2 ...   5225     61 15.3   dE    1 Simbad
194.89679 27.98063  Mm 192254        3 ...   7355    110  4.5   dE    1 Simbad
194.90867 27.94901  Mm 194749        3 ...   6128     79  7.1   dE    1 Simbad
      ...      ... ...    ...  ... ... ...    ...    ...  ...   ... ...    ...
195.09079 28.07819  PM  32799        3 ...     --     --  nan   cE    1 Simbad
195.10258 28.06191  PM  20411        3 ...     --     --  nan         1 Simbad
195.13754 27.99557  PM 160003        2 ...     --   

In [25]:
#read s spectrum fits file

filename='/home/xsh/下载/351110104.fits'
tchfits=fits.open(filename)
log_wv0=tchfits[0].header['CRVAL1']
log_dwv=tchfits[0].header['CD1_1']

sp=tchfits[0].data.copy()

N=len(sp[0,:])
wv=10**(log_wv0+np.arange(0,N,1)*log_dwv)

fig=plt.figure(figsize=[10,4])
ax=fig.add_subplot(111)
ax.plot(wv,sp[0,:],'k-')
ax.set_xlim([4000,9000])
fig.show()

In [29]:
#write table fits

from astropy.table import Table
t=Table([[1,2],[4,5],[7,8]],names=('a','b','c'))
t.write('table3.fits',format='fits')

c1=fits.Column(name='a',array=np.array([1,2]),format='K')
c2=fits.Column(name='b',array=np.array([4,5]),format='K')
c3=fits.Column(name='c',array=np.array([7,8]),format='K')
t=fits.BinTableHDU.from_columns([c1,c2,c3])
t.writeto('table4.fits')

OSError: File exists: table3.fits